version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 'WXvlwM-HF7fwKbyyKoR6J7'
      MYSQL_DATABASE: customersList
      MYSQL_USER: customersUser
      MYSQL_PASSWORD: 'R5M#I?kPWQ8oE5e?y&7lQQOd'
    ports:
      - "3326:3306"
    volumes:
      - db_data:/var/lib/mysql3
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: CustomersList.Api/Dockerfile
    container_name: customers_list_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://0.0.0.0:3000
      - ConnectionStrings__DefaultConnection=Server=mysql_db;Port=3306;Database=customersList;User=customersUser;Pwd=R5M#I?kPWQ8oE5e?y&7lQQOd;
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
